#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: mysql-config
#data:
#  mysql-url: mysql-service

apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
data:
  host : mysql
  dbName: employee