apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-deployment
  labels:
    app: restful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restful
  template:
    metadata:
      labels:
        app: restful
    spec:
      containers:
        - name: restful
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-url
---
apiVersion: v1
kind: Service
metadata:
  name: restful-service
spec:
  type: NodePort
  selector:
    app: restful
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100